#!/usr/bin/python

import numpy as np
from pyds9 import *
import cosmos as c
import sys
import os

display=DS9()
args=sys.argv[1:]
dfile=args[0]
if dfile.count('_') > 0:
    dfile += '_'
image=os.environ['COSMOS_IMAGE_DIR'] +'/' + dfile
frame='1'
hd=plane=0
if(len(args)>1):
    if args[1].isdigit:
        frame=args[1]
        args=sys.argv[3:]
    i=-1
    for arg in args:
        i+=1
        if("-h" in arg):
            hd=int(args[i+1])
            continue
        elif("-p" in arg):
            plane=int(args[i+1])
            continue
c.dispn(image,display,hd,plane,frame,8)
