#!/usr/bin/python

import numpy as np
from astropy.io import fits
import sys
import os
import re

segment=0
args=sys.argv[1:]
dfile=args[0]
hd=plane=0
if(len(args)>1):
    if '' in args[1]:
        segment=1
        b=args[1].replace('[','')
        a=b.replace(']','')
        pairs=a.split(',')
        xrange=pairs[0].split(':')
        xmin=int(xrange[0])
        xmax=int(xrange[1])+1
        yrange=pairs[1].split(':')
        ymin=int(yrange[0])
        ymax=int(yrange[1])+1
        print dfile, xrange, yrange
    if args[1].isdigit():
        frame=args[1]
        args=sys.argv[3:]
    i=-1
    for arg in args:
        i+=1
        if("-h" in arg):
            hd=int(args[i+1])
            continue
        elif("-p" in arg):
            plane=int(args[i+1])
            continue
imagename=os.environ['COSMOS_IMAGE_DIR'] +'/' + dfile + '.fits'
filename=imagename
hdu=fits.open(filename)
omage=hdu[hd].data
dims=omage.ndim
if(dims>2):
    image=omage[plane,:,:]
else:
    image=omage
if segment:
    print image[ymin:ymax,xmin:xmax]
else:
    print image

def die(message):

    print message, "\n"
    sys.exit(0)
